# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'map_data',
            },
        ),
        migrations.CreateModel(
            name='MapDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'map_definitions',
            },
        ),
        migrations.CreateModel(
            name='MapOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'map_owners',
            },
        ),
        migrations.CreateModel(
            name='SchemaFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_field', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('field_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schema_fields',
            },
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MapDefinition')),
                ('map_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MapOwner')),
            ],
            options={
                'db_table': 'schema_versions',
            },
        ),
        migrations.RenameField(
            model_name='mapobject',
            old_name='map',
            new_name='map_instance',
        ),
        migrations.RemoveField(
            model_name='mapinstance',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='mapinstance',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='mapinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mapinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='data',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='mapinstance',
            name='retrieval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapinstance',
            name='source_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='guid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterModelTable(
            name='mapinstance',
            table='map_instances',
        ),
        migrations.AlterModelTable(
            name='mapobject',
            table='map_object',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='schemafields',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.SchemaVersion'),
        ),
        migrations.AddField(
            model_name='mapdefinition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MapOwner'),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='map_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MapInstance'),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='map_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MapObject'),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='schema_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.SchemaFields'),
        ),
        migrations.AddField(
            model_name='mapinstance',
            name='map_definition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.MapDefinition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapinstance',
            name='schema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.SchemaVersion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mapdata',
            unique_together=set([('map_instance', 'map_object', 'schema_field')]),
        ),
    ]
