# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20160925_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaFields',
            new_name='SchemaField',
        ),
    ]
