# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20160926_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapinstance',
            name='retrieval_date',
        ),
    ]
